### ISSUE TITLE
Job conflict with register center

### ISSUE THREAD

**Issue by xiebin2015** [apache/shardingsphere-elasticjob#1960]
There is a problem with elasitcjob 3. X. I have two nodes for task scheduling service. The first node starts normally, and the second node reports job conflict with register center exception. What is the reason?

**Comment by sunkai-cai** [comment]
hi  @xiebin2015 ，

Could you show the exception infomation。

**Comment by xiebin2015** [comment]
org.apache.shardingsphere.elasticjob.infra.exception.JobConfigurationException: Job conflict with register center. The job 'authorizerRefreshTokenJob' in register center's class is 'com.gf.job.simple.AuthorizerRefreshTokenJob$$EnhancerBySpringCGLIB$$25dfddd8', your job class is 'com.gf.job.simple.AuthorizerRefreshTokenJob$$EnhancerBySpringCGLIB$$e59941b5'
	at org.apache.shardingsphere.elasticjob.lite.internal.config.ConfigurationService.checkConflictJob(ConfigurationService.java:86)
	at org.apache.shardingsphere.elasticjob.lite.internal.config.ConfigurationService.setUpJobConfiguration(ConfigurationService.java:70)
	at org.apache.shardingsphere.elasticjob.lite.internal.setup.SetUpFacade.setUpJobConfiguration(SetUpFacade.java:66)
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.JobScheduler.<init>(JobScheduler.java:84)
	at org.apache.shardingsphere.elasticjob.lite.api.bootstrap.impl.ScheduleJobBootstrap.<init>(ScheduleJobBootstrap.java:36)
	at org.unicorn.framework.elastic.reg.SimpleJobReg.prepareScheduleJobBootstrap(SimpleJobReg.java:28)
	at org.unicorn.framework.elastic.reg.AbstractJobReg.regJob(AbstractJobReg.java:33)
	at org.unicorn.framework.elastic.init.UnicornInitJob.start(UnicornInitJob.java:56)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:893)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:163)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at com.gf.job.Application.main(Application.java:18)

**Comment by TeslaCN** [comment]
This issue is duplicated with #1909.

**Comment by xiebin2015** [comment]
Thank you, but I can't seem to find out how to solve this problem there. Can you help me give a solution?

**Comment by TeslaCN** [comment]
@xiebin2015 
This problem has been fixed by #1932 and merged into master.

**Comment by xiebin2015** [comment]
Sorry, I read #1932 it and still don't understand how to solve it. My Maven dependencies are as follows
![image](https://user-images.githubusercontent.com/14512197/129341907-467be845-6efd-44d8-b5b4-d8cd61d97a04.png)

**Comment by xiebin2015** [comment]
hi 你好，对于Job conflict with register center这个问题，我想到一种解决方法，之后没有再出现这个问题，但是我不确定的是这样是否带来了其他问题，请指教，谢谢。
解决方法是在节点启动过程中初始化job任务之前先检查job是否持久化到zookeeper中了，如果存在则先删除，再重新创建job。
![image](https://user-images.githubusercontent.com/14512197/129499977-af0ae25b-be1d-45ce-900a-203cfcb6cc24.png)

**Comment by sunkai-cai** [comment]
hi @xiebin2015,

Thanks for your proposal.
I think #1932  can resolve you problem. May be you can try it When next version released, or build it for youself.

**Comment by xiebin2015** [comment]
hi 我看了 #1932 的描述，但是我还是不看懂，我需要如何调整才能解决这个问题，debug过程中发现org.apache.shardingsphere.elasticjob.lite.internal.config.ConfigurationService.checkConflictJob方法里面比较新旧两个jobClassName是否一致，不一致则直接抛出异常了，在多节点启动的情况下，获得的jobclassName肯定会不一样，导致这里必然会抛出Job conflict with register center，能否给出一个更加详细的解决方案，谢谢

**Comment by xiebin2015** [comment]
Hi, I solved this problem by customizing the four classes of schedulejobbootstrap, jobscheduler, setupfacade and configurationservice, and rewriting the checkconflictjob method of configurationservice. After a simple test, no problems and effects were found. I want to know what problems the author mainly wants to solve in comparing the stored class names in ZK?

**Comment by sunkai-cai** [comment]
Hi @xiebin2015 ,

welcome you question. 

the `SpringProxyJobClassNameProvider` class can resolve your problem, it can get the job original class name by cglib or jdk dynamic proxy object.  you can look at it :)

**Comment by xiebin2015** [comment]
Hi, I finally understand #1932 what spring proxyjobclassnameprovider means. By adding the SPI configuration of spring proxyjobclassnameprovider, I solved the problem of job conflict with register center. Thank you very much! In addition, I would like to ask which version of this problem will be repaired?

**Comment by sunkai-cai** [comment]
in next version 3.1.0 ，you can waiting for release

**Comment by xiebin2015** [comment]
OK, I look forward to the release of the new version. Thank you very much for your help

**Comment by mzygQAQ** [comment]
> hi 你好，对于Job conflict with register center这个问题，我想到一种解决方法，之后没有再出现这个问题，但是我不确定的是这样是否带来了其他问题，请指教，谢谢。 解决方法是在节点启动过程中初始化job任务之前先检查job是否持久化到zookeeper中了，如果存在则先删除，再重新创建job。 ![image](https://user-images.githubusercontent.com/14512197/129499977-af0ae25b-be1d-45ce-900a-203cfcb6cc24.png)

集群你这么做不就是只有一台机器能注册上最后

**Comment by CheukBinLi** [comment]
每次启动覆盖不是更好吗？

在 ***@***.***> 写道：

**Comment by mzygQAQ** [comment]
> 每次启动覆盖不是更好吗？ 在 ***@***.***> 写道：
> […](#)
> > hi 你好，对于Job conflict with register > center这个问题，我想到一种解决方法，之后没有再出现这个问题，但是我不确定的是这样是否带来了其他问题，请指教，谢谢。 > 解决方法是在节点启动过程中初始化job任务之前先检查job是否持久化到zookeeper中了，如果存在则先删除，再重新创建job。 > ![image](https://user-images.githubusercontent.com/14512197/129499977-af0ae25b-be1d-45ce-900a-203cfcb6cc24.png) 集群你这么做不就是只有一台机器能注册上最后 -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: [#1960 (comment)](https://github.com/apache/shardingsphere-elasticjob/issues/1960#issuecomment-957071941)

同一个应用 集群中的不同进程起来的到的代理类的名称每次都不一样 假设集群3台机器 只有最后一台机器才注册上了，前两次都被覆盖了不就变成单点了
